# Generated by Django 3.2.8 on 2021-10-20 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import photo_album.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='video/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), photo_album.validators.validate_image])),
                ('photo_webp', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['webp'])])),
                ('thumbnail', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), photo_album.validators.validate_image])),
                ('views', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
